[package]
name = "c_ffi_demo"
version = "2.0.0"
authors = ["Peter Doherty <pdoherty@protonmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
libc = "^0.2"

[build-dependencies]
cc = "1.0.91"
